version: "3.9"
services:
  service-mysql:
    image: "mysql:8.0"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=api
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3326:3306"
    networks:
      - network1
  api:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=collaudo
    ports:
      - "9080:9080"
    networks:
      - network1
    depends_on:
      - service-mysql
    restart: always
volumes:
  mysql-data:
  
networks:
  network1:
    name: jdv-network
    external: true
